### ISSUE TITLE
Predict.Yaml

### ISSUE THREAD

**Issue by arrrrr3186** [weepiess/Official-Code-for-StyleFlow-For-Content-Fixed-Image-to-Image-Translation#16]
How should i defined configs/predict.yaml'

do we need pass src and target images both here as well?

**Comment by SolicTous** [comment]
Agreed, same question

**Comment by arrrrr3186** [comment]
Just make the below changes in yaml file, you are good to go 
rootA: /Dataset/train_src.txt

rootB: /Dataset/train_target.txt

**Comment by SolicTous** [comment]
I see. Maked files to test)
But it's need really a lot of GPU memory)

Seems closed issue
